### ISSUE TITLE
[4월 10일 문제]

### ISSUE THREAD

**Issue by YounggLee** [algo-algo/algorithm-practice#5]
담당자: 이영진, 박민규, 이현진

**Comment by ramelHJ** [comment]
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWxQ310aOlQDFAWL

**Comment by pmk9257** [comment]
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV-eALvKRnsDFAXr&categoryId=AV-eALvKRnsDFAXr&categoryType=CODE&problemTitle=2983&orderBy=FIRST_REG_DATETIME&selectCodeLang=ALL&select-1=&pageSize=10&pageIndex=1

**Comment by YounggLee** [comment]
https://leetcode.com/problems/the-skyline-problem/
